# Generated by Django 5.1.1 on 2026-09-08 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearts', models.BigIntegerField(default=0, verbose_name='Текущие сердца')),
                ('total_clicks', models.BigIntegerField(default=0, verbose_name='Всего кликов')),
                ('total_hearts_collected', models.BigIntegerField(default=0, verbose_name='Всего собрано сердец')),
                ('purchased_ids', models.JSONField(default=list, verbose_name='Купленные предметы')),
                ('equipped', models.JSONField(default=dict, verbose_name='Надетые предметы по слотам')),
                ('save_epoch', models.CharField(blank=True, default='', max_length=64, verbose_name='Эпоха сейва (UUID текущей сессии)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_save', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Сохранение игрока',
                'verbose_name_plural': 'Сохранения игроков',
            },
        ),
    ]
